### ISSUE TITLE
Add new flag and BSL

### ISSUE THREAD

**Issue by bufutda** [bufutda/bufbot-issues#110]
* @_source, which contains `twitch`, `whisper`, or `discord` depending on the invoking message's source
* BSL OPCODE `mul.v.ivf` v = v * ivf
* BSL OPCODE `div.v.ivf` v = v / ivf
* BSL OPCODE `mod.v.ivf` v = v % ivf

**Comment by gracenotes** [comment]
Would these still be simple changes to make? There are definitely a few commands still I've been wanting to make that would benefit from all of these, especially ones that are time-related.
