### ISSUE TITLE
!nextstream - Schedule

### ISSUE THREAD

**Issue by Styxx** [bufutda/bufbot-issues#39]
Ouputs time until next stream in hours and minutes
Needs to be turned on in config && Requires streamer (or mod) to input schedule data.
(inputed data times should be standardized to EDT to make everything easier)

i.e.
!nextstream
[Streamer's] next scheduled stream is supposed to be in 2 hours and 23 minutes!

Command is unusable while stream is live.

**Comment by bufutda** [comment]
okie. what if I just implement custom API support, and make a bufutda.com endpoint for rex's nextstream?

**Comment by Styxx** [comment]
English please.

**Comment by bufutda** [comment]
addcom r nextstream -w https://www.bufutda.com/bananasaurus_rex/nextstream.php

add -w functionality in 3.0.8.1
