### ISSUE TITLE
Resubshout

### ISSUE THREAD

**Issue by firynth** [bufutda/bufbot-issues#78]
Can't be changed with config

**Comment by firynth** [comment]
Subshout can't either?

**Comment by firynth** [comment]
Changing things in config doesn't spit anything back

**Comment by firynth** [comment]
Config seems to be entirely broken, broadcaster can't change it either.

**Comment by firynth** [comment]
resubshout case has

log.debug("std", config, 

in it versus just

log.debug(config, 

like every other case.

**Comment by bufutda** [comment]
missing a column in the db
