### ISSUE TITLE
Highlight That ids

### ISSUE THREAD

**Issue by firynth** [bufutda/bufbot-issues#90]
Don't apparently interact with list or del at this time. At least the numerical values.

**Comment by firynth** [comment]
`  } else if (/^[0-9]$/.test(msg.args[2])) {`
needs to be changed to 
`  } else if (/^[0-9]+$/.test(msg.args[2])) {`

for delete. Need to look at list more to figure out the problem with it.

**Comment by bufutda** [comment]
Resolved in https://github.com/bufutda/bufbot/commit/82ea2e9ea360a29669f20bffa0f5b74b1084e567
